### ISSUE TITLE
Adding Keepalivespec

### ISSUE THREAD

**Issue by HanYangZhao** [fviard/sllurp#10]
Hi,

I'm trying to add Keepalivespec inside 'SET_READER_CONFIG'. In the original version of sllurp, it was like this : 

llrp.py

        msg = {
            'SET_READER_CONFIG': {
                'ResetToFactoryDefaults': False,
                'ReaderEventNotificationSpec': {
                    'EventNotificationState': {
                        'HoppingEvent': False,
                        'GPIEvent': False,
                        'ROSpecEvent': False,
                        'ReportBufferFillWarning': False,
                        'ReaderExceptionEvent': False,
                        'RFSurveyEvent': False,
                        'AISpecEvent': False,
                        'AISpecEventWithSingulation': False,
                        'AntennaEvent': False,
                        ## Next one will only be available
                        ## with llrp v2 (spec 1_1)
                        #'SpecLoopEvent': False,
                    },
                },
                'KeepaliveSpec': {
                    'KeepaliveTriggerType': 1,
                    'TimeInterval': llrp_keepalive_interval
                },
            }
        }

llrp_proto.py

	def encode_KeepaliveSpec(msg):
	    msgtype = Message_struct['KeepaliveSpec']['type']
	    msg_header = '!HH'
	    msg_header_len = struct.calcsize(msg_header)
	    data = struct.pack('!B',msg['KeepaliveTriggerType'])
	    data += struct.pack('!I',msg['TimeInterval'])
	    data = struct.pack(msg_header, msgtype,
	                       len(data) + msg_header_len) + data
	    return data

	Message_struct['KeepaliveSpec'] = {
	    'type': 220,
	    'fields': [
	        'KeepaliveTriggerType',
	        'TimeInterval'
	    ],
	    'encode': encode_KeepaliveSpec
	}

I see in the new llrp_proto.py, there is the following

	# v1.1:17.2.6.4 KeepaliveSpec Parameter
	Param_struct['KeepaliveSpec'] = {
	    'type': 220,
	    'fields': [
	        'KeepaliveTriggerType',
	        'TimeInterval',
	    ],
	    'decode': basic_param_decode_generator(ubyte_uint_unpack,
	                                           'KeepaliveTriggerType',
	                                           'TimeInterval')
	}
I guessing i'll need to add the encoding call here. However I'm having a bit of trouble understand how the data is being encoded. In the original version you could calculate the size of each data field and append, but the refactor seems to do something different. Do you have any pointer?

Thanks

**Comment by fviard** [comment]
Hi @HanYangZhao , indeed, there is just the decoder so far, but that will be very very easy to add the encoder that you need.
I think that would be good as "exercice" for you to look at doing it to understand the new system.
But let me know if it is still not clear after digging a little.

For a pointer to help you, I have provided a lot of details there:
https://github.com/ransford/sllurp/pull/146#issuecomment-563493449
Also, it's on another topic, but it could be interesting for you to also to follow this issue:
https://github.com/fviard/sllurp/issues/9
as I'm helping someone else understanding how to use the new things in llrp_proto.py

Just tell me if I was not clear enough in the previous links, and that some points are still confusing.

**Comment by HanYangZhao** [comment]
https://github.com/fviard/sllurp/pull/13

I fixed a typo in the ImpinjBLEVersion subtype as well

**Comment by fviard** [comment]
@HanYangZhao Thanks for having found this typo. That explains a weird behavior I had decoding ImpinjHubVersions and for what I did a hack as I was thinking that the reader was at fault.
Thanks to you, i will be able to clean that up!

**Comment by fviard** [comment]
Thanks for the commit and sorry for the long delay for my review.
As you added a few changes that are not directly related to the feature of Keepalivespec itself, I'm a little confuse on the best way to do the review.
So, I will do a little bit directly in the code review and the rest here.

**Comment by fviard** [comment]
More comments than the one in the review:
- "get_connection_status" and "_is_connected":
You can't have that and should not provide it to the client as the situation is a little bit more complicated than that.
The connection status is complex as there are multiple factors to be taken into account:
connecting/disconnecting state, state machine in the "reader"/"inventory" state, error states, ...
Currently, the client should use the function `is_alive()` to determine if the device is "connected" and "alive".

- Internally, it would be better to not create a new variable `infinite_reconnect_attempts` and just make smarter usage of max_retry.
For example, in config there could be a `reconnect_max_retry` variable that could be configurable and using that with a value like "-1" for "infinite"

- For the new callbacks, I'm not a very big fan of adding a lot of callbacks.
For temporary connection events, I don't like that too much, because the use could try/want to perform an action in response to such a message and create nasty situations. But if you still think that the callback would be needed, at least we should create a more generic callback that could cover other notifications to the client or at least a single one with a parameter to indicate if it is a notification of lost_conn, recoverd_conn, anything else on the conn.

For the rest, the basics protocol things of keepalive and also the ble fix, that is all good, so if ever you want and that you can split the PR I could already merge that part.

**Comment by HanYangZhao** [comment]
Thanks. Let me split the merge

**Comment by HanYangZhao** [comment]
I have a question about is_alive(). It seems that when the antenna loses connection. The is_alive() still remains True. Is that the correct behavior?

**Comment by fviard** [comment]
What do you mean with "antenna loses connection"? You  mean if one antenna is unplugged?
is_alive is related/similar to software "threads"  isalive meaning.
It is not directly related to the state of the reader itself, but we can say that it gives an indication of the state of the connection with the reader.

In a normal code, the "main thread" of your application, when you ask a "connect" to the reader, a new "thread"/instance will start to run in loop in parallel. You can be in this state even if you are not really in an active connection because your are currently in "connecting", "disconnecting", "reconnecting" state.
is_alive will then be false only when this sub-thread/instance will exit.

So, we can say that it does not really monitor the reader/connection itself, but just, from the main program, it indicates if something is running in parallel or if we are all clear to exit the program/run a new connection to the reader/things like that.

If you wanted to monitor the exact timings when the connection is in effect active and the inventory running, the best is to look at llrp events like rospec_start. But the only thing that you might not notice is the start of a period of "lost connection" as logically you will not receive an event for that from the reader.

**Comment by HanYangZhao** [comment]
Ah I see now. Thanks

**Comment by HanYangZhao** [comment]
I'm trying to figure out how to fix the callback issues. The reason I added those callbacks is because I have an application built on top of sllurp. In my application I send the status of the reader so having those callbacks is handy in case the reader goes offline. I agree that it should be one generic callback instead of multiples one, but what would be the correct structure ? A dict of list?

`self._connection_event_callbacks = {'lost_conn': [], 'recovered_conn': [], 'disconnect':[]}`

**Comment by HanYangZhao** [comment]
I'm trying to figure out how to fix the callback issues. The reason I added those callbacks is because I have an application built on top of sllurp. In my application I send the status of the reader so having those callbacks is handy in case the reader goes offline. I agree that it should be one generic callback instead of multiples one, but what would be the correct structure ? A dict of list?

`self._connection_event_callbacks = {'lost_conn': [], 'recovered_conn': [], 'disconnect':[]}`

**Comment by fviard** [comment]
In fact, looking at the code, I think that you can do this feature on your application side without changing sllurp.
I just see that now, with a fast look, so I might be wrong.
What you can do is register a callback using "add_state_callback" for the following states:
`LLRPReaderState.STATE_DISCONNECTED` and `LLRPReaderState.STATE_INVENTORYING`

As I see that when the connection is lost, the first thing we do is ensuring to switch the state back to disconnected.
I think that keeping track of the order of the calls and the is_alive state, you can be able to differentiate between lost/recovered etc...
The only important thing is to not try to do "reader" actions during these callback to not risk having race condition.
For example, if you get a "disconnected" **state** callback, you should not automatically try to call connect/disconnect of the reader, because we are just in a intermediate state.
You can just take real automatic action after a real "disconnect_callback" or when is_alive is False. 

I hope that I'm clear enough, otherwise don't hesite to ask for more details about my idea.

**Comment by HanYangZhao** [comment]
Great I'll try that and get back to you

**Comment by HanYangZhao** [comment]
Finally got around to test it. It works as you suggested. Thanks

**Comment by fviard** [comment]
:+1:
