### ISSUE TITLE
sllurp fork without twisted reactor

### ISSUE THREAD

**Issue by avasygn** [fviard/sllurp#2]
Hello @fviard,
Do you know this fork of sllurp ? https://github.com/EMS-TU-Ilmenau/sllurp
It works without twisted reactor like your fork and there is a GUI to test it. 
Maybe there are some interesting stuff for your development.

**Comment by fviard** [comment]
Hi, I did not know about it.
Regarding the non-GUI part, it is not very advanced, but it had encountered/fixed a few annoying things of sllurp. But today, these things are already fixed, so not useful anymore, but would have been if I had found it earlier.

Regarding the GUI, I haven't test it yet because it depends on things particular to this version. But I'm curious to test when i will have a little bit of time.

**Comment by fviard** [comment]
Btw, I googled a little bit and I have found that they have published an article that is very interesting:
https://www.researchgate.net/publication/333349000_A_versatile_automated_cost-effective_testing_platform_for_hands-on_UHF_RFID_measurements

It looks like that, they did all the RFID tests that I would have had done, and how I would have like to do them. So, very great and interesting!

**Comment by avasygn** [comment]
Thank you for sharing me this article. It is very interesting to know how they did their tests.
