### ISSUE TITLE
TypeError: unsupported operand type(s) for >>: 'tuple' and 'int'

### ISSUE THREAD

**Issue by pBogey** [fviard/sllurp#8]
Hello,

I was using Ben Ransford's sllurp and decided to give this version a try, because I can't wrap my head around twisted.

I am using a Zebra FX9500 fixed RFID reader. Running `sllurp inventory <host>` resulted in the error from the title: 

> TypeError: unsupported operand type(s) for >>: 'tuple' and 'int'

This happened when `decode_C1G2TagInventoryStateAwareSingulationAction` was called, from llrp_proto, because `ISA` was `(0,)` in my case.

I modified the fucntion to:

```
def decode_C1G2TagInventoryStateAwareSingulationAction(data, name=None):
    logger.debugfast('decode_C1G2TagInventoryStateAwareSingulationAction')
    par = {}

    ISA = ubyte_unpack(data)[0]
    par['I'] = (ISA >> 7) and 'State_B' or 'State_A'
    par['S'] = ((ISA >> 6) & 1) and 'Not_SL' or 'SL'
    par['A'] = ((ISA >> 5) & 1) and 'All' or 'No'

    return par, 
```

and it worked well afterwards. Well, I mean I still need to find a way to[ stop the inventory process, after some time](https://github.com/ransford/sllurp/issues/136) :)

I guess the `decode_C1G2TagInventoryStateAwareSingulationAction` function needs to check ISA type before the byte shifting happens or add a try-except clause. I've started to learn programming 1,5 years ago, so I'll let you decide how to best handle it :).

**Comment by fviard** [comment]
Thank you @pBogey, it was a bug and you were right about the fix.
When using unpack, it always return a tuple even if there is a single element, that was missed inside this function.

I did not encounter this issue because this Parameter is not reported by Impinj Readers.
I have not tested with anything else than an Impinj Reader, so your feedback and experience is valuable. Let me know if you encounter another issue.

Regarding your other issue of not knowing how to stop the reader after a specific time, you can have a look at how cli commands of sllurp are implemented in the "verb" folder:
https://github.com/fviard/sllurp/tree/fviard-develop-v2/sllurp/verb

Especially in inventory.py
There is the try/catch block where we connect the reader with reader.connect().
From that point, the reader(s) start to do the inventory asynchronously, and the main "thread" (ie the code that you are in, in inventory.py) is free to continue doing what it wants.
Reader things will happen in the background, and just call the callbacks when needed.

Then, you have a big "while" loop, this is not something needed for the operation, but it is just there to ensure that the "main thread" with not finish when the inventory is still active in the background and at the same time, exit if ever all reader have finished.

So in this loop, what we do is just look at all the readers that are still "alive" (ie connected/active/inventorying), and then call "join(xx)" on it.
This join(xx) is just a fonction that wait when the reader is still alive for up to xx seconds..

So in your case, the simplest way to do what you want, is just to put something like this between the reader connection and the big while loop:
```

from time import sleep
sleep(30) # sleep 30 seconds
reader.disconnect()
```

Btw, if you would like to help extend sllurp to support some custom parameters or features that are specific to the zebra readers, i would be interested to get from you some specific information/test coming from the reader. You might also even be able to contribute to the code yourself as it is not that hard, once you understand how to convert what you see in the spec to code.
If that is something you would be ok do to, let me know and we can open a specific dedicated issue for that.

**Comment by pBogey** [comment]
> Btw, if you would like to help extend sllurp to support some custom parameters or features that are specific to the zebra readers, i would be interested to get from you some specific information/test coming from the reader. 

Sure, I'll be glad to help, however I can. 

> You might also even be able to contribute to the code yourself as it is not that hard, once you understand how to convert what you see in the spec to code.
If that is something you would be ok do to, let me know and we can open a specific dedicated issue for that.

Man, I'll be happy to be able to contribute, it will mean I have reached a good proficiency level. I actually tried to compare the llrp_proto.py file in this repo vs the one in Ben's repo and there are some thing I didn't quite get.

I think the best way for me to help is running some tests or something, finding some issues and trying to debug. This way I will also get familiar with the code.

**Comment by fviard** [comment]
Awesome :-)
Normally, things will look a lot simpler once you understand  a little bit more what is doing the code and why.
I created the issue #9 to continue this subject there.
